# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodePushDemo' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodePushDemo

  

  platform :ios, '9.0'
  target 'CodePushDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CodePushDemo-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodePushDemo-tvOS

  target 'CodePushDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
